# Generated by Django 6.0.6 on 2026-06-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0005_completedproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
