# Generated by Django 6.0.6 on 2026-06-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0007_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
