# Generated by Django 6.0.6 on 2026-06-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0008_alter_emailverification_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='is_verified',
        ),
    ]
